export { default as Navbar } from './Navbar.vue'
// export { default as Sidebar } from './Sidebar/index.vue'
export { default as TagsView } from './tagsView.vue'
export { default as AppMain } from './AppMain.vue'
export { default as AppMainNoAnimate} from './AppMainNoAnimate.vue'
